# Generated by Django 5.2.7 on 2025-10-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=250)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
